---
title: "分析报告"
author: "张三"
date: "2020年3月"
institute: 中南财经政法大学统计与数学学院
csl: ./style/chinese-gb7714-2015-numeric.csl
css: ./style/markdown.css
bibliography: [./Bibfile.bib]
eqnPrefixTemplate: ($$i$$)
link-citations: true
linkReferences: true
chapters: true
tableEqns: false
autoEqnLabels: false
classoption: "aspectratio=1610"
---

```{r setup, echo=F, purl=F}
knitr::opts_knit$set(root.dir = getwd())
knitr::opts_chunk$set(echo = TRUE, results = 'hide')
knitr::opts_chunk$set(warning = FALSE, message=FALSE)
knitr::opts_chunk$set(fig.align="center"
                      ## ,out.width="0.9\\textwidth" # latex
                      ,out.width="60%" # for both latex and html
                      ,fig.width=5, fig.height=3
                      )
```

```{r prepare, echo=F, purl=F}
rm(list=ls())
options(digits=4)
options(scipen=100)
graphics.off()
Sys.setlocale("LC_ALL", "Chinese")
```

**TODO**

- [x] 表格如何输出
- [ ] Bib文件如何整理

R代码

```{r, results='markup'}
2+3
```

python代码

```{python, results='markup'}
3+5
```

python图形

```{python}
import matplotlib.pyplot as plt
plt.plot([0,1])
```

# 使用说明

输出表格

```{r, results='markup'}
knitr::kable(head(trees))
```

行内公式 $\alpha+\hat{\beta}$ 。

行间公式

$$\bar x = \sum_{i=1}^n x_i +\bar y$$

$$X \sim N(0,1)$$


## 文件结构 

## 使用方法

# 参考文献
[//]: # (\bibliography{Bibfile})
